services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

  ploc:
    build:
      context: .
      dockerfile: Dockerfile
    image: ploc:latest
    ports:
      - 5173:5173
    env_file:
      - .env

volumes:
  postgres-data:
