services:
  plock:
    image: ghcr.io/eliottwantz/plock:latest
    ports:
      - 5173:5173
    env_file:
      - .env
    environment:
      - DB_URL=postgresql://postgres:postgres@host.docker.internal:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 5
  mailpit:
    image: axllent/mailpit:latest
    restart: on-failure
    container_name: mailpit
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  postgres_data: null
